apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orders-sqlstore
spec:
  type: state.sqlserver
  version: v1
  metadata:
  - name: connectionString
    value: "Server=sql;Initial Catalog=dapr;Persist Security Info=False;User ID=sa;Password=y4dPrhPM55GhWSQw;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=True;Connection Timeout=30;"
